spring.application.name=transaction-service

logging.level.root=INFO
logging.level.com.smartpay.transactionservice=DEBUG
logging.file.name=logs/transaction-service.log

spring.datasource.url=jdbc:postgresql://localhost:5432/smartpay
spring.datasource.username=postgres
spring.datasource.password=SohanM@5579#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true